services:
  app:
    build:
      target: prod
    container_name: monitur-pesquisas-prod 
    restart: unless-stopped
    ports:
      - "3000:3000"
      
  postgres:
    container_name: monitur-pesquisas-db-prod 
    ports:
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

volumes:
  postgres-prod-data:
    name: monitur-pesquisas-prod-data