version: "3.8"
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: monitur-pesquisas-local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: sh -c "pnpm exec prisma generate && pnpm dev"

  postgres:
    image: postgres:15
    container_name: monitur-pesquisas-db
    restart: always
    environment:
      # Credenciais ambiente de DESENVOLVIMENTO
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
