services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitur-pesquisas
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: monitur-pesquisas-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
