services:
  app:
    build:
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm exec prisma generate && pnpm dev"

  postgres:
    ports:
      - "5432:5432"