services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: monitur-pesquisas-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: monitur-pesquisas-db-prod
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

volumes:
  postgres-prod-data:
    name: monitur-pesquisas-prod-data
